// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Z9kY2N1zRaZUvtClNdPXWhwBmQYLz_k',
    appId: '1:1014003207552:web:5d7552feb4fc2955924565',
    messagingSenderId: '1014003207552',
    projectId: 'riverpod2-todo',
    authDomain: 'riverpod2-todo.firebaseapp.com',
    storageBucket: 'riverpod2-todo.appspot.com',
    measurementId: 'G-FQ2SMJNELM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIxmLsIt4AAY32WfLQDAR-iTO5SG75Uv4',
    appId: '1:1014003207552:android:06c39c47951919fa924565',
    messagingSenderId: '1014003207552',
    projectId: 'riverpod2-todo',
    storageBucket: 'riverpod2-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX9ZMCEzCrsx-QRdnr-e-WBAmmAcv6__8',
    appId: '1:1014003207552:ios:e008578d1ac1e347924565',
    messagingSenderId: '1014003207552',
    projectId: 'riverpod2-todo',
    storageBucket: 'riverpod2-todo.appspot.com',
    iosClientId: '1014003207552-s32kggqv8etncqrpifdmc8tcj1sj5g9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpod2',
  );
}
